version: '3'
services:
  nbe:
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      - TZ=America/Toronto
      - SMTP_USER=
      - SMTP_PASS=
    volumes:
      - ./db.sqlite3:/root/db.sqlite3
